const GET_POKEMONS = "GET_POKEMONS";
const GET_TYPES = "GET_TYPES";
const SEARCH_NAME = "SEARCH_NAME";
const CHANGE_PAGE = "CHANGE_PAGE";
const FILTER_POKEMONS = "FILTER_POKEMONS";
const FILTER_POKEMONS_ORIGIN = "FILTER_POKEMONS_ORIGIN";

module.exports = {
    GET_POKEMONS,
    GET_TYPES,
    CHANGE_PAGE,
    SEARCH_NAME,
    FILTER_POKEMONS,
    FILTER_POKEMONS_ORIGIN
}